name: Release App
on:
  push:
    tags: "*"

env:
  IMAGE_NAME: myjettools/docker-statistics-collector
  BUILD_PATH: docker-statistics-collector

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Get the version
        id: get_version
        run: |
          cd ${BUILD_PATH}
          echo ::set-output name=VERSION::$(echo ${GITHUB_REF_NAME})

      - name: Updating version
        run: |
          cd ${BUILD_PATH}
          sed -i -e 's/^version = .*/version = "${{ steps.get_version.outputs.VERSION }}"/' Cargo.toml

      - name: Install Protoc
        uses: arduino/setup-protoc@v1            
      - run: |
          cd ${BUILD_PATH}
          cargo build --release

      - name: Docker login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASS: ${{ secrets.DOCKER_PASSWORD }}
        run: |  
          cd ${BUILD_PATH}        
          echo "$DOCKER_PASS" | docker login --username "$DOCKER_USER" --password-stdin   
      - name: Docker Build and Publish
        run: |          
          cd ${BUILD_PATH}
          docker build -t ${IMAGE_NAME}:${{ steps.get_version.outputs.VERSION }} .
          docker push ${IMAGE_NAME}:${{ steps.get_version.outputs.VERSION }}
        

